In [1]:
import numpy as np

## 1차원 배열 만들기

In [2]:
ar = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print(ar)
ar

[0 1 2 3 4 5 6 7 8 9]


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
print(type(ar))
type(ar)

<class 'numpy.ndarray'>


numpy.ndarray

In [5]:
data = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
data = list(range(10))
print(type(data), data)

<class 'list'> [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [6]:
answer = []
for di in data:
    answer.append(2 * di)
print(answer)

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]


In [7]:
x = np.array(data)
print(x)

[0 1 2 3 4 5 6 7 8 9]


In [8]:
# numpy에 곱하기
print(x * 2)

[ 0  2  4  6  8 10 12 14 16 18]


In [9]:
# list에 곱하기
print(2 * data)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [10]:
a = np.array([1, 2, 3])
b = np.array([10, 20, 30])

In [11]:
2 * a + b

array([12, 24, 36])

In [12]:
list_a = [1, 2, 3]
list_b = [10, 20, 30]
2 * list_a + list_b

[1, 2, 3, 1, 2, 3, 10, 20, 30]

In [14]:
print(a)
print(a == 2)

[1 2 3]
[False  True False]


In [18]:
print(b)
print(b > 10)

[10 20 30]
[False  True  True]


In [16]:
print((a == 2) & (b > 10))

[False  True False]


In [17]:
print((a == 2) | (b > 10))

[False  True  True]


## 2차원 배열 만들기

In [21]:
c = np.array([[0, 1, 2], [3, 4, 5]])
print(c)
c

[[0 1 2]
 [3 4 5]]


array([[0, 1, 2],
       [3, 4, 5]])

In [22]:
len(c)

2

In [24]:
print(c[0])
print(len(c[0]))

[0 1 2]
3


#### 연습문제

In [29]:
x = np.array([[10, 20, 30, 40], [50, 60, 70, 80]])
x

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

## 다차원 배열 만들기

In [30]:
d = np.array([[[1, 2, 3, 4],
             [5, 6, 7, 8],
             [9, 10, 11, 12]],
            [[11, 12, 13, 14],
            [15, 16, 17, 18],
            [19, 20, 21, 22]]])
print(d)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[11 12 13 14]
  [15 16 17 18]
  [19 20 21 22]]]


In [31]:
d1 = [[1, 2, 3, 4],
      [5, 6, 7, 8],
      [9, 10, 11, 12]]
d2 = [[11, 12, 13, 14],
      [15, 16, 17, 18],
      [19, 20, 21, 22]]
d = np.array([d1, d2])
d

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[11, 12, 13, 14],
        [15, 16, 17, 18],
        [19, 20, 21, 22]]])

## 차원의 배열과 크기 알아보기

In [34]:
print(a)
print(a.ndim) # 배열의 차원
print(a.shape) # 차원의 요소

[1 2 3]
1
(3,)


In [36]:
print(c)
print(c.ndim)
print(c.shape)

[[0 1 2]
 [3 4 5]]
2
(2, 3)


## 배열의 인덱싱

In [39]:
a = np.array([0, 1, 2, 3, 4])
print(a)
print(a[2])
print(a[-1])

[0 1 2 3 4]
2
4


In [41]:
a = np.array([[0, 1, 2],
             [3, 4, 5]])
print(a[0,0])
print(a[0, 1])
print(a[-1, -1])

0
1
5


## 배열 슬라이싱

In [42]:
a = np.array([[0, 1, 2, 3],
             [4, 5, 6, 7]])
print(a)
print(a[0, :]) # 첫번째 행 전체
print(a[:, 1]) # 첫번째 열 전체
print(a[1, 1:])
print(a[:2, :2])

[[0 1 2 3]
 [4 5 6 7]]
[0 1 2 3]
[1 5]
[5 6 7]
[[0 1]
 [4 5]]


#### 연습문제

In [46]:
m = np.array([[0, 1, 2, 3, 4],
              [5, 6, 7, 8, 9],
              [10, 11, 12, 13, 14]])
print(m[1, 2])

7


In [51]:
print(m[2, 4])
print(m[-1, -1])
print(m[2, 4], m[-1, -1])

14
14
14 14


In [48]:
print(m[1, 1:3])

[6 7]


In [49]:
print(m[:2, -2:])

[[3 4]
 [8 9]]


## 회귀분석

In [52]:
# 최소제곱
import numpy as np

x = [2, 4, 6, 8]
y = [81, 93, 91, 97]

# x와 y의 평균
mx = np.mean(x)
my = np.mean(y)
print('x의 평균값: ', mx)
print('y의 평균값: ', my)

# a = x - x의 평균 합의 제곱
divisor = sum([(mx - i)**2 for i in x])

x의 평균값:  5.0
y의 평균값:  90.5


In [60]:
# 기울기 공식의 분자
def top(x, mx, y, my):
    d = 0
    for i in range(len(x)):
        d += ((x[i] - mx) * (y[i] - my))
    return d
#dividend = top(x, mx, y, my)
dividend = sum((x[i] - mx) * (y[i] - my) for i in range(len(x)))
print('분모: ', divisor)
print('분자: ', dividend)

# 기울기와 y 절편 구하기
a = dividend / divisor
b = my - (mx * a)

print('기울기 a =', a)
print('y 절편 b =', b)

분모:  20.0
분자:  46.0
기울기 a = 2.3
y 절편 b = 79.0


#### 최소제곱법 실습

In [76]:
x = [1, 2, 3, 4, 5, 6, 7, 8]
y = [0.2, 0.3, 0.5, 0.6, 0.9, 0.95, 1.1, 1.5]

mx = np.mean(x)
my = np.mean(y)
print('x의 평균값: ', mx)
print('y의 평균값: ', my)

divisor = sum([(mx - i)**2 for i in x])
dividend = sum((x[i] - mx) * (y[i] - my) for i in range(len(x)))
print('분모: ', divisor)
print('분자: ', dividend)


a = dividend / divisor
b = my - (mx * a)
print('기울기 a =', a)
print('y 절편 b =', b)

def size(week):
    cal = a * week + b
    if cal < 30:
        return round(cal,3)
    else:
        return 30

# 예측 문제    
print('15주차 예상크기: ', size(15))
print('22주차 예상크기: ',size(22))
print('77주차 예상크기: ',size(77))
print('200주차 예상크기: ',size(200))
# 5주차 예상크기
print('5주차 예상크기와 실크기의 차 :',round((size(5) - 0.9), 3))

x의 평균값:  4.5
y의 평균값:  0.7562500000000001
분모:  42.0
분자:  7.375
기울기 a = 0.17559523809523808
y 절편 b = -0.03392857142857131
15주차 예상크기:  2.6
22주차 예상크기:  3.829
77주차 예상크기:  13.487
200주차 예상크기:  30
5주차 예상크기와 실크기의 차 : -0.056
