# 영상 매칭과 추적
## 1. 비슷한 그림 찾기 : 영상 전체의 비교

In [2]:
### 평균 해시로 변환 = 영상을 특정 크기로 축소 → 전체의 평균값을 구해서 각 픽셀이 평균보다 작은지 큰지 구분하는 이진수 수로 만들기
import cv2

# 이미지 불러오기
img = cv2.imread('./picture/pistol.jpg')
# 이미지 그레이 스케일로 변환
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

# 이미지 16x16으로 사이즈 변경
gray = cv2.resize(gray, (16, 16))
# 이미지 전체의 평균 구하기
avg = gray.mean()
# 이미지의 픽셀값이 크면 1을 대입
bin = 1 * (gray > avg)
print(bin)

# 2진수 문자열을 16진수 문자열로 변환
dhash = []
for row in bin.tolist():
    s = ''.join([str(i) for i in row])
    dhash.append('%02x'%(int(s, 2)))

dhash = ''.join(dhash)
print(dhash)

cv2.imshow('pistol', img)
cv2.waitKey(0)
cv2.destroyAllWindows()

[[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 1 0 0 1 1 1 1 1 1]
 [1 1 0 0 0 0 0 1 1 1 1 1 1 1 1 1]
 [1 1 0 0 0 0 0 1 1 1 1 1 1 1 1 1]
 [1 1 0 0 0 0 0 0 0 1 1 1 1 1 1 1]
 [1 1 0 0 0 0 1 1 1 1 1 1 1 1 1 1]
 [1 1 0 0 0 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 0 0 0 1 1 1 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 0 0 0 1 1 1 1 1 1 1 1 1 1 1]]
ffff8000800080008000813fc1ffc1ffc07fc3ffc7ffc7ff87ff87ff87ffc7ff


In [5]:
# 사물 영상 중에서 권총 영상 찾기
import cv2
import numpy as np
import glob

# 영상 읽기 및 표시
img = cv2.imread('./picture/pistol.jpg')
cv2.imshow('query', img)

# 비교할 영상들이 있는 경로
search_dir = './picture/101_ObjectCategories'

# 아마자룰 16x16 크기의 평균 해시로 변환
def img2hash(img):
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    gray = cv2.resize(gray, (16, 16))
    avg = gray.mean()
    bi = 1 * (gray>avg)
    return bi

# 해밍 거리 측정 함수
def hamming_distance(a, b):
    a = a.reshape(1, -1)
    b = b.reshape(1, -1)
    # 같은 자리의 값이 서로 다른 것들의 합
    distance = (a != b).sum()
    return distance

# 권총 영상의 해시 구하기
query_hash = img2hash(img)

# 이미지 데이터셋 디렉터리의 모든 영상 파일 경로
img_path = glob.glob(search_dir + '/**/*.jpg')

# 이미지 데이터 한장한장 가지고 오기!
for path in img_path:
    # 데이터셋 영상 한 개를 읽어ㅓ 표시
    img = cv2.imread(path)
    cv2.imshow('searching...', img)
    cv2.waitKey(5)
    # 데이터셋 영상 한 개의 해시
    a_hash = img2hash(img)
    # 해밍 거리 계산 = 넣어준 이미지 한장 vs 이미지 데이터 셋에서 꺼낸 이미지 한 장
    dst = hamming_distance(query_hash, a_hash)
    # 만약 해밍거리가 25% 안이면 출력
    if dst/256 < 0.25:
        print(path, dst/256)
        cv2.imshow(path, img)

cv2.destroyWindow('searching...')
cv2.waitKey(0)
cv2.destroyAllWindows()

./picture/101_ObjectCategories/BACKGROUND_Google/image_0398.jpg 0.234375
./picture/101_ObjectCategories/revolver/image_0037.jpg 0.2421875
./picture/101_ObjectCategories/revolver/image_0021.jpg 0.171875
./picture/101_ObjectCategories/revolver/image_0023.jpg 0.21875
./picture/101_ObjectCategories/revolver/image_0019.jpg 0.23828125
./picture/101_ObjectCategories/revolver/image_0017.jpg 0.23828125
./picture/101_ObjectCategories/revolver/image_0064.jpg 0.18359375
./picture/101_ObjectCategories/revolver/image_0022.jpg 0.21484375
./picture/101_ObjectCategories/revolver/image_0018.jpg 0.1953125
./picture/101_ObjectCategories/revolver/image_0033.jpg 0.2421875
./picture/101_ObjectCategories/revolver/image_0001.jpg 0.2421875
./picture/101_ObjectCategories/revolver/image_0034.jpg 0.23046875
./picture/101_ObjectCategories/revolver/image_0031.jpg 0.21875
./picture/101_ObjectCategories/revolver/image_0068.jpg 0.24609375
./picture/101_ObjectCategories/revolver/image_0015.jpg 0.24609375
./picture/101_O

In [12]:
### 템플릿 매칭 = 물체가 있는 영상을 준비해두고 물체가 매칭되는 위치를 찾는것!
# 따라서 템플릿(물체 이미지)는 하상 입력 영상보다 작아야함!!!!
import numpy as np
import cv2

# 이미지 불러오기
img = cv2.imread('./picture/figures.jpg')
# 이미지 내에서 찾을 타겟 이미지 불러오기
template = cv2.imread('./picture/taekwonv1.jpg')
# 템플릿의 가로, 세로 지정
th, tw = template.shape[:2]
cv2.imshow('template', template)

# 검출 방법 : 상관계수 매칭, 상관관계 매칭, 
methods = ['cv2.TM_CCOEFF_NORMED', 'cv2.TM_CCORR_NORMED', 'cv2.TM_SQDIFF_NORMED']

# 메서드에 있는 방법과 순서를 하나씩 꺼내오기
for i, method_name in enumerate(methods):
    img_draw = img.copy()
    # eval : 문자열을 식으로 실행해주는 애
    method = eval(method_name)
    # matchTemplate = 입력 영상에서 템플릿 영상을 찾기
    res = cv2.matchTemplate(img, template, method)
    # result = 이미지 크기 - 템플릿 크기 + 1 한 이차원 배열 → 여기서 최소 최대 값을 구할 수  있다.
    min_val, max_val, min_loc, max_loc = cv2.minMaxLoc(res)
    print(method_name, min_val, max_val, min_loc, max_loc)

    # 상관계수 매칭과 제곱 차이 매칭 → 최소값이 좋은 매칭
    if method in [cv2.TM_SQDIFF, cv2.TM_SQDIFF_NORMED]:
        top_left = min_loc
        match_val = min_val
    # 그 외의 방법은 최대값이 좋은 매칭
    else:
        top_left = max_loc
        match_val = max_val

    # 매칭 좌표를 구해서 사각형 표시
    bottom_right = (top_left[0] + tw, top_left[1] + th)
    cv2.rectangle(img_draw, top_left, bottom_right, (0,0,255), 2)
    # 매칭 포인트 표시
    cv2.putText(img_draw, str(match_val), top_left, cv2.FONT_HERSHEY_PLAIN, 2, (0,255,0), 1, cv2.LINE_AA)
    cv2.imshow(method_name, img_draw)

cv2.waitKey(0)
cv2.destroyAllWindows()

cv2.TM_CCOEFF_NORMED -0.1780252307653427 0.5131933093070984 (42, 0) (208, 43)
cv2.TM_CCORR_NORMED 0.827332615852356 0.9238022565841675 (85, 6) (208, 43)
cv2.TM_SQDIFF_NORMED 0.17028295993804932 0.36860838532447815 (208, 43) (86, 7)


## 2. 영상의 특징과 키 포인트 : 지역적 특징을 표현할 수 있는 방법

In [14]:
### 코너 특징 검출
import cv2
import numpy as np

# 이미지 불러와서 그레이 스케일로 변환
img = cv2.imread('./picture/house.jpg')
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

# 해리스 코너 검출 : 소벨 미분으로 엣지 검출 → 엣지의 경사도 변화량 측정 → 변화량이 큰 부분이 코너
# cornerHarris(이미지, 이웃 픽셀 번위, 소벨 미분 커널 크기, 코너 상수)
corner = cv2.cornerHarris(gray, 2, 3, 0.04)
# 변화량 결과의 최대값 10% 이상의 좌표 구하기
coord = np.where(corner > 0.1*corner.max())
coord = np.stack((coord[1], coord[0]), axis=-1)

# 코너 좌표에 동그리미 그리기
for x, y in coord:
    cv2.circle(img, (x,y), 5, (0,0,255), 1, cv2.LINE_AA)

# 변화량을 영상으로 표현하기 위해서 0~255 정규화
corner_norm = cv2.normalize(corner, None, 0, 255, cv2.NORM_MINMAX, cv2.CV_8U)

# 화면에 출력
corner_norm = cv2.cvtColor(corner_norm, cv2.COLOR_GRAY2BGR)
merged = np.hstack((corner_norm, img))
cv2.imshow('Harris Corner', merged)
cv2.waitKey()
cv2.destroyAllWindows()

In [15]:
### 시-토마시 코너 검출
import cv2
import numpy as np

# 이미지 불러오기
img = cv2.imread('./picture/house.jpg')
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

# goodFeaturesToTrack(이미지, 얻고싶은 코너 수, 스레시홀드값, 코너간 최소 거리_)
corners = cv2.goodFeaturesToTrack(gray, 80, 0.01, 10)
# 이때 좌표값이 실수로 되어있기 때문에 정수형으로 변환
corners = np.int32(corners)

# 코너들에 동그라미 표시하기
for corner in corners:
    x, y = corner[0]
    cv2.circle(img, (x, y), 5, (0, 0, 255), 1, cv2.LINE_AA)

# 이미지 보여주기
cv2.imshow('Corners', img)
cv2.waitKey()
cv2.destroyAllWindows()

In [16]:
### GFTTDetector
import cv2
import numpy as np

# 이미지 불러오기
img = cv2.imread('./picture/house.jpg')
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

# goodFeaturesToTrack 함수로 구현된 특징 검출기
gftt = cv2.GFTTDetector_create()
# 키포인트 검출 = detect(이미지)
keypoints = gftt.detect(gray, None)
# drawKeypoints(이미지, 키포인트 리스트, 이미지, 색상)
img_draw = cv2.drawKeypoints(img, keypoints, None)

cv2.imshow('GFTTDector', img_draw)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [17]:
### FAST로 키 포인트 검출 = 미분 대신 픽셀을 중심으로 특정 개수의 픽셀로 원그리기 → 특정 개수 이상 연속되면 코너
import cv2
import numpy as np

# 이미지 불러오기
img = cv2.imread('./picture/house.jpg')
# 이미미 그레이 스케일로 변환
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

# FASt 특징 검출기 생성 = FastFeatureDetector()
fast = cv2.FastFeatureDetector_create(50)
# detect로 키포인트 검출하기
keypoints = fast.detect(gray, None)
# 키초인트에 원 그리기
img = cv2.drawKeypoints(img, keypoints, None)


cv2.imshow('Fast', img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [18]:
### SimpleBlobDetector = 연결된 픽셀 그룸을 말한다! 자잘한 객체는 노이즈, 특정 크기 이상만!
import cv2
import numpy as np

# 이미지 불러와서 그레이 스케일로 변환
img = cv2.imread('./picture/house.jpg')
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

#  BLOB 검출기 생성자
detector = cv2.SimpleBlobDetector_create()
keypoints = detector.detect(gray)
img = cv2.drawKeypoints(img, keypoints, None, (0,0,255), flags=cv2.DRAW_MATCHES_FLAGS_DRAW_RICH_KEYPOINTS)

cv2.imshow('Blob', img)
cv2.waitKey()
cv2.destroyAllWindows()

In [21]:
### SimpleBlobDetector + 필터 옵션
import cv2
import numpy as np

# 이미지 불러와서 그레이스케일로 변환
img = cv2.imread('./picture/house.jpg')
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

# BLOB 검출 필터 파라미터 생성
params = cv2.SimpleBlobDetector_Params()

# 경계값 조정 = 10부터 240까지 5씩 증가
params.minThreshold = 10 # 최소 경계값
params.maxThreshold = 240 # 최대 경계값
params.thresholdStep = 5 # 증가 값

# 면적 필터를 켜고 최소 값 지정
params.filterByArea = True # 면적 필터 옵션
params.minArea = 200 # 범위의 면적만 BLOB 검출 = 최소 200 이상은 되어야 검출

# 컬러, 볼록 비율, 원형 비율 필터 옵션 끄기
params.filterByColor = False # 밝기를 이용한 필터
params.filterByConvexity = False # 볼록 비율 필터
params.filterByInertia = False # 관성 비율 필터
params.filterByCircularity = False # min-max 범위의 원형 비율만 BLOB 검출

# 필터 파라미터로 BLOB 검출기 생성
detector = cv2.SimpleBlobDetector_create(params)
# 키 포인트 검출
keypoints = detector.detect(gray)
# 키 포인트 그리기
img_draw = cv2.drawKeypoints(img, keypoints, None, None, cv2.DRAW_MATCHES_FLAGS_DRAW_RICH_KEYPOINTS)

cv2.imshow('Blob with Params', img_draw)
cv2.waitKey(0)
cv2.destroyAllWindows()

## 3. 디스크립터 추출기

In [9]:
### 특징 디스크립터 = 키포인트를 매칭에 사용하기 위해 주변 픽셀을 일정한 블록으로 나누어 각 블록에 속한 픽셀의그레디언트 히스토그램을 계산한 것
# 키포인트: 영상의 특징이 있는 픽셀의 좌표와 주변 픽셀과의 관계에 대한 정보 (size, angle)

### SIFT로 키포인트 및 디스크립터 추출
# import cv2
# import numpy as np

# img = cv2.imread('./picture/house.jpg')
# gray= cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

# sift = cv2.xfeatures2d.SIFT_create()
# keypoints, descriptor = sift.detectAndCompute(gray, None)
# print('keypoint:', len(keypoints), 'desciptor:', descriptor.shape)
# print(descriptor)

# img_draw = cv2.drawKeypoints(img, keypoints, None, flags=cv2.DRAW_MATCHES_FLAGS_DRAW_RICH_KEYPOINTS)

# cv2.imshow('SIFT', img_draw)
# cv2.waitKey()
# cv2.destroyAllWindows()

In [ ]:
### SURF

In [ ]:
### ORB

## 4. 특징 매칭

Found existing installation: opencv-python 4.5.3.56
Uninstalling opencv-python-4.5.3.56:
  Would remove:
    /home/sydney/.virtualenvs/jupyter/lib/python3.8/site-packages/cv2/*
    /home/sydney/.virtualenvs/jupyter/lib/python3.8/site-packages/opencv_python-4.5.3.56.dist-info/*
    /home/sydney/.virtualenvs/jupyter/lib/python3.8/site-packages/opencv_python.libs/libQt5Core-d92f2856.so.5.15.0
    /home/sydney/.virtualenvs/jupyter/lib/python3.8/site-packages/opencv_python.libs/libQt5Gui-ca084835.so.5.15.0
    /home/sydney/.virtualenvs/jupyter/lib/python3.8/site-packages/opencv_python.libs/libQt5Test-9d4ee57e.so.5.15.0
    /home/sydney/.virtualenvs/jupyter/lib/python3.8/site-packages/opencv_python.libs/libQt5Widgets-0e1d98b5.so.5.15.0
    /home/sydney/.virtualenvs/jupyter/lib/python3.8/site-packages/opencv_python.libs/libQt5XcbQpa-70670cdb.so.5.15.0
    /home/sydney/.virtualenvs/jupyter/lib/python3.8/site-packages/opencv_python.libs/libX11-xcb-1ae4fd0e.so.1.0.0
    /home/sydney/.virtualenvs

## 5. 객체 추적

In [ ]:
y